# Uncomment the next line to define a global platform for your project

platform :ios, '8.0'
  target 'SwiftDown' do
  
  use_frameworks!

  pod 'AFNetworking'		, '3.1.0'
  pod 'SDWebImage'			, '3.8.2'
  pod 'YYModel'				, '1.0.4'
  pod 'FMDB'				, '2.6.2'
  pod 'MBProgressHUD'		, '1.0.0'
  pod 'pop'					, '1.0.9'
  pod 'YYImage'				, '1.0.4'
  pod 'Alamofire'			, '~> 4.3.0'
  pod 'ReactiveCocoa'		, '6.0.1'
  pod 'HMSegmentedControl'	, '~> 1.5.3'

end
